### ISSUE TITLE
[Weak Supervision] Enable weak supervision for multi_label text classification

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1144]
1. Weak supervision with multi_labels rules (CLIENT)
2. Define rules with multi_label classes (UI + SERVER)

## Tasks

- [x] Enable multi label selection for "Define Rules" (API and UI)
- [x] Adapt precision and correct/incorrect metrics (UII and API)
- [x] Adapt WeakLabelMatrix and LabelModel (Client)

**Comment by Amelie-V** [comment]
Single/multi labels

- [x] Allow deselecting all labels while I'm creating or editing a rule (show Save disabeled)
- [x] Change are to is : "This query with these labels is already saved as rule"
