### ISSUE TITLE
Change css theme

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1543]

**Comment by Amelie-V** [comment]
QA:

### Desktop - TOC

- [x] Up TOC font size to 14 px.

- [x] Use grey #484848 for hover and active style link. **Add it on hover too**

- [x] Change BG color of active anchor (yellow highlight) to grey (same grey than used in highlight sidebar

- [x] Write CONTENTS like this "Contents" and use the blue #4C4EA3
- [ ] Change # for the previous icon. 

### Dark mode

- [x] Menu titles in White
- [x] Link style : on hover use the same light blue, a bit clearer
       
### Code area

- [x] Apply "Material"
- [x] Adapt padding
- [x] If necessary change "material" BG color to a lighter grey

### Table

- [x] Align header to the left


### Layout

- [x] Center layout
- [x] Adapt sidebar padding, just like in previous vs
- [x] Reduce anchor central column

General

- [x] Dark mode : show "Content" in white
- [x] Search mode: improve contrast. L.M : "Search" in blue color link D.M: "Search" in white color (instead of grey)
- [x] Remove scroll bar
- [ ] Use the # color BG as hover menu color
- [x] Add Padding around img, Code area, info block
- [x] Padding around code is still not affecting all the code areas

- [ ] Use grey #484848 for hover and active style link. Add it on hover too
