### ISSUE TITLE
Usage telemetry

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1629]
## Description

Record several usage metrics for the python client and API usage.

The registered event must be well defined and documented to users and could be disabled at any moment.

## Tasks

- [ ] Add metrics documentation (how to disable, which metrics will be collected,...)
- [ ] Minimal event to register:  `/api/me`, `/api/datasets/.../bulk` and API errors
- [ ] Define metrics component (encapsulate communication with segment.io, environment settings,...)
- [ ] Configure the segment.io sources and destinations

**Comment by frascuchon** [comment]
@dvsrepo  You should start to work from this branch https://github.com/recognai/rubrix/tree/feat/usage-telemetry (I cannot create a draft PR since the branch has no changes)

**Comment by dvsrepo** [comment]
@frascuchon I've added a base doc. This needs to be completed with an exhaustive list of fields, methods and also the specif way of opting-in and out.
