### ISSUE TITLE
[API] Normalize and simplify server API endpoints

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1842]
- Groups by tasks
- More rest oriented
- Propose new actions (delete by query, partial updates - annotate/validate )
- Prepare for other protocols (graphQL, gRPC, ...)

See recognai/rubrix#756 

## Tasks 

- [ ] Create new /api/v1  endpoints
- [ ] Group current api endpoints under v1 path
- [ ] Deprecate current api endpoints
- [ ] Generate a proper openapi documentation
- [ ] Include api docs in as rubrix doc section
- [ ] Client using new api/v2
- [ ] UI using new api/v2

**Comment by frascuchon** [comment]
Here my normalization proposal. The idea is group endpoints by functionality instead of task.

```python
# Datasets management
"GET    /datasets/:task1,:task2"            # Get datasets
"POST   /datasets/:task"                    # Create a new dataset (with records)
"GET    /datasets/:task/:id"                # Get a dataset (info)
"PUT    /datasets/:task/:name"              # replace dataset (info) (neither task, name)
"PATCH  /datasets/:task/:name"              # Update tags/metadata
"DELETE /datasets/:task/:name"              # delete a dataset (and its records)
"POST   /datasets/:task/:name:copy"         # copy a dataset
"POST   /datasets/:task/:name(:open|:close)"   # open/close a dataset (free es resources)


# Logging
"POST   /datasets/:task/:name"         # bulk a set of records
"PUT    /datasets/:task/:name/:id"     # replace a record
"PATCH  /datasets/:task/:name/:id"     # update some record attributes (to discuss)

# Search
"POST   /datasets/:task/:name/search"  # search records in dataset
"POST   /datasets/:task/:name/view"    # dataset view for a search (similar to search but return ALL records)

# Weak supervision / labelling
"GET    /datasets/:task/:name/labeling/rules"   # Get dataset rules
"POST   /datasets/:task/:name/labeling/rules"   # Create a new rule for dataset
"GET    /datasets/:task/:name/labeling/rules/:query"  # Get a dataset rule
"PATCH  /datasets/:task/:name/labeling/rules/:query"  # Partial update of dataset rule
"DELETE /datasets/:task/:name/labeling/rules/:query"  # Delete a dataset rule
"GET    /datasets/:task/:name/labeling/rules:summary" # Compute dataset rules metrics
"GET    /datasets/:task/:name/labeling/rules/:query:summary" # Compute rule metrics

# Metrics
"GET    /datasets/:task/:name/labeling/metrics"   # Get defined dataset metrics/dimensions?
"GET    /datasets/:task/:name/labeling/metrics/:metric" # Get the metric info (accepted params)
"POST   /datasets/:task/:name/labeling/metrics/:metric:summary" # Compute the dataset metric

```

cc @dvsrepo @dcfidalgo

**Comment by dcfidalgo** [comment]
Looks tidy and nice! :100:

**Comment by dvsrepo** [comment]
is this still relevant or up to date? @frascuchon
