### ISSUE TITLE
Spans question in Feedback datasets

### ISSUE THREAD

**Issue by davidsbatista** [recognai/rubrix#1868]
I need to annotate data where for each document I need to annotate named-entities (i.e., token level classification) and also a set of labels (doc-level classification)

How can one achieve this with rubrix, as far as I understood you need to have two different collections, for the two different tasks, and then, after annotating and exporting them, you need to merge the annotations.

Is there any way to have this done inside rubrix - also on the interface?
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla-server/issues/45
- [ ] https://github.com/argilla-io/argilla-server/issues/49
- [ ] https://github.com/argilla-io/argilla/issues/4616
- [ ] https://github.com/argilla-io/argilla/issues/4618
- [ ] https://github.com/argilla-io/argilla/issues/4635
- [ ] https://github.com/argilla-io/argilla-server/issues/55
- [ ] https://github.com/argilla-io/argilla-server/issues/61
- [ ] https://github.com/argilla-io/argilla-server/issues/64
- [ ] https://github.com/argilla-io/argilla-server/issues/73
- [ ] https://github.com/argilla-io/argilla-server/issues/75
- [ ] https://github.com/argilla-io/argilla/issues/4651
```

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/discussions/1969

**Comment by davidsbatista** [comment]
so we are now 2, the number of users who already suggested this task, we're growing 😄

**Comment by davidberenstein1957** [comment]
Keep [this issue](https://github.com/argilla-io/argilla/issues/1750) updated

**Comment by davidberenstein1957** [comment]
@davidsbatista We added this to Q3 2023 in [our Roadmap](https://github.com/orgs/argilla-io/projects/10/views/1)

**Comment by davidsbatista** [comment]
nice, thanks @davidberenstein1957 for keeping this as a feature 👍🏽 I think it will pay off

**Comment by davidberenstein1957** [comment]
@davidsbatista we are hard at work at tackling this issue at the moment. Would any of you be interested in providing some feedback and pointers w.r.t. what you would expect from the implementation? If so, could you ping me on Slack or send me an email at [david@argilla.io](mailto:david@argilla.io)?

**Comment by davidsbatista** [comment]
@davidberenstein1957 I currently don't have much time since I start a new project, but I can in between pull a docker image with the new features and try to run it and test it

**Comment by nataliaElv** [comment]
@davidsbatista As you can probably see, we're working to deliver this feature in the next release. We'd love to know what you think of how the feature looks 😄 You can try it out following the instructions here: https://rubrixworkspace.slack.com/archives/C05DHJ3LGQM/p1710504136136119
