### ISSUE TITLE
👬 Similarity search in Feedback datasets

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3028]
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/pull/3750
- [ ] https://github.com/argilla-io/argilla/pull/3744
- [ ] https://github.com/argilla-io/argilla/pull/3799
- [x] [TEST] Make the `elasticsearch` engine tests work in the CI pipeline
- [ ] https://github.com/argilla-io/argilla/issues/3761
- [x] [FEATURE] Add `GET /api/v1/datasets/{dataset_id}/vectors-settings` endpoint
- [x] [FEATURE] Add `DELETE /api/v1/vectors-settings/{vector_settings_id}` endpoint
- [x] [FEATURE] Update `POST /api/v1/datasets/{dataset_id}/records` endpoint to include vectors in body (https://github.com/argilla-io/argilla/pull/4022)
- [ ] https://github.com/argilla-io/argilla/pull/3765
- [x] New endpoint `GET /api/v1/records/:record_id`  to fetch the reference record
- [ ] https://github.com/argilla-io/argilla/issues/4071
- [ ] https://github.com/argilla-io/argilla/issues/4066
- [x] [HIGH] Define `dataset.add_vector_settings` method in the Python SDK https://github.com/argilla-io/argilla/pull/4055
- [x] [HIGH] Allow to create records with vectors in Python SDK https://github.com/argilla-io/argilla/pull/4043
- [x] [HIGH][FEATURE] Update `POST /api/v1/me/datasets/{dataset_id}/records/search` endpoint to allow vector search (https://github.com/argilla-io/argilla/pull/4019)
- [x] Unify `index_record` and `set_record_vectors` for the search engine
- [x] [HIGH] Allow partial update for record vectors (not needed to pass all the vectors structure for a record) https://github.com/argilla-io/argilla/pull/4104
- [ ] https://github.com/argilla-io/argilla/issues/4085
- [ ] https://github.com/argilla-io/argilla/issues/4102
- [ ] https://github.com/argilla-io/argilla/issues/4020
- [ ] https://github.com/argilla-io/argilla/issues/4114
- [ ] https://github.com/argilla-io/argilla/issues/4051
- [ ] https://github.com/argilla-io/argilla/issues/4069
- [ ] https://github.com/argilla-io/argilla/issues/4105
- [ ] https://github.com/argilla-io/argilla/issues/4106
- [ ] https://github.com/argilla-io/argilla/issues/4119
- [ ] https://github.com/argilla-io/argilla/issues/4123
- [ ] Review Validations (dimensions, vector names, ...)
- [ ] Add documentation
- [ ] Create use case tutorial
```

Main feature branch PR https://github.com/argilla-io/argilla/pull/3815
