### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3098]
## Links:
- Notion: https://www.notion.so/argilla/Save-draft-responses-24a65885163b4790918bdabe0e8e373f?pvs=4

Refs #2895 

### Description
Allow users to save partial responses. This will help to not lose data in the annotation progress.

### User stories
- As a user, I want that my partial responses get automatically saved, so that I don't lose progress if I navigate within the dataset or close the dataset.
- As a user, I want to see any partial responses that I left when I start a new annotation session, so that I can take breaks and/or close the application without losing progress.
- As a user, I want to see some indication that my partial response has been saved, so that I know when I can close without losing progress.

### Acceptance criteria
- [ ] Continuously save the form while it is in an active state (i.e. brown outline in the UI).
- [ ] Auto-saved responses will be saved with the status Draft in the backend.
- [ ] The pending queue will show records without responses & in draft.

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/3259
- [ ] https://github.com/argilla-io/argilla/issues/3648
- [ ] https://github.com/argilla-io/argilla/pull/3623
```

**Comment by frascuchon** [comment]
![image](https://github.com/argilla-io/argilla/assets/2518789/4b6fbf05-5f53-4cf7-8b38-1f51df8e691c)

**Comment by nataliaElv** [comment]
@frascuchon @damianpumar Please, fill in the task section with the issues needed to complete this epic.
