### ISSUE TITLE
Python client `FeedbackDataset` refactor to simplify new user workflows implementation

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3456]
```[tasklist]
### Tasks
- [ ] Create base class `FeedbackDatasetBase` and let `FeedbackDataset` as a working-locally dataset
- [ ] Implement the `ArgillaFeedbackDataset` class to work with datasets defined in argilla
- [ ] Adapt and deprecate properties and methods for `FeedbackDataset` (`fetch_records, `argilla_id`,...)
```
