### ISSUE TITLE
[FEATURE] Improve CLI to include basic operations

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3579]
**Is your feature request related to a problem? Please describe.**
Right now the CLI of Argilla mainly supports management operations for the server like migrating the database or creating users directly connecting to the database.

It would be good to be able to login in an Argilla server from the CLI and later be able to perform some operations like creating users or workspaces.
```
$ argilla login https://dev.argilla.io/ --username gabrielmbmb
Password:
Logged in https://dev.argilla.io/
$ argilla workspaces create my_project
Created `my_project` workspace in https://dev.argilla.io/
$ argilla users create --username gabrielmbmb --workspace my_project
User `gabrielmbmb` created!
```

**Describe the solution you'd like**
Update the CLI interface to add a login command that will store the credentials locally in order to be able to call later other commands for creating workspaces, users, etc. In addition, these locally store credentials could be used as a fallback if `rg.init` is not called.

The current command for creating users directly connecting to the database should be moved under `argilla database users` or similar.

**Additional context**
Right now, you need to create a python script to create users and workspaces, which is mostly fine, but in some cases it can be a bit cumbersome.

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/3581
- [ ] https://github.com/argilla-io/argilla/issues/3583
- [ ] https://github.com/argilla-io/argilla/issues/3584
- [ ] https://github.com/argilla-io/argilla/issues/3585
- [ ] https://github.com/argilla-io/argilla/issues/3586
- [ ] https://github.com/argilla-io/argilla/issues/3587
- [ ] https://github.com/argilla-io/argilla/issues/3690
- [ ] https://github.com/argilla-io/argilla/issues/3588
- [ ] https://github.com/argilla-io/argilla/issues/3589
- [ ] https://github.com/argilla-io/argilla/issues/3590
- [ ] https://github.com/argilla-io/argilla/issues/3591
- [ ] https://github.com/argilla-io/argilla/issues/3670
- [ ] https://github.com/argilla-io/argilla/issues/3691
- [ ] https://github.com/argilla-io/argilla/issues/3669
- [ ] https://github.com/argilla-io/argilla/issues/3704
- [ ] https://github.com/argilla-io/argilla/issues/3680
- [ ] https://github.com/argilla-io/argilla/issues/3675
- [ ] https://github.com/argilla-io/argilla/issues/3722
- [ ] https://github.com/argilla-io/argilla/pull/3758
```

**Comment by davidberenstein1957** [comment]
@gabrielmbmb Do you feel this would be a good first issue?

**Comment by gabrielmbmb** [comment]
@davidberenstein1957 I think after we create the initial structure, we could break this task down into subtasks and those would be good first issues.

EDIT: I've added a few subtasks, let me know what you think :) I'll add the login command probably tomorrow, the rest of the tasks could be good first issues. What do you think?
