### ISSUE TITLE
⏳ Filtering and sorting using custom metadata info

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3748]
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/3798
- [x] Get metadata fields from backend
- [ ] https://github.com/argilla-io/argilla/issues/3796
- [ ] https://github.com/argilla-io/argilla/pull/3841
- [ ] https://github.com/argilla-io/argilla/issues/3844
- [ ] https://github.com/argilla-io/argilla/pull/3949
- [x] Use metadata filter title instead of name [FRONTEND]
- [ ] https://github.com/argilla-io/argilla/pull/3811
- [ ] https://github.com/argilla-io/argilla/pull/3813
- [ ] https://github.com/argilla-io/argilla/pull/3816
- [x] Index metadata values on record creation (#3816)
- [x] Enable metadata filtering from `SearchEngine` (#3816)
- [x] Adapt search records endpoint including metadata query params (#3816)
- [ ] https://github.com/argilla-io/argilla/pull/3819
- [x] Enable metadata filtering from get records endpoints `GET /api/v1/datasets/:dataset_id/records` and `GET /api/v1/me/datasets/:dataset_id/records`  (#3819)
- [ ] https://github.com/argilla-io/argilla/pull/3825
- [x] Sort by `last_updated` and `inserted_at` values (https://github.com/argilla-io/argilla/pull/3825)
- [x] Add basic `settings` support for metadata properties, including `max` and `min` for integer and float types and a value list for terms
- [x] Dataset with metadata in quickstart script (https://github.com/argilla-io/argilla/pull/3830/commits/e421d77dd1c9258c3e5ee3112d903c725bbcb99f)
- [ ] https://github.com/argilla-io/argilla/issues/3835
- [x] Sort by metadata property values
- [ ] https://github.com/argilla-io/argilla/issues/3898
- [ ] https://github.com/argilla-io/argilla/issues/3859
- [x] Add `allow_extra_metadata` support (API + SDK)
- [x] Add new endpoint to delete metadata properties (https://github.com/argilla-io/argilla/pull/3911)
- [x] Add `visible_for_annotator` support (https://github.com/argilla-io/argilla/pull/3924)
- [x] Update policies to support metadata property visibility for annotators
- [x] Add client validations for SDK
- [x] Allow to update metadata for records (https://github.com/argilla-io/argilla/pull/3946)
- [x] Add `sort-by` support in the python client (https://github.com/argilla-io/argilla/pull/3925)
- [x] [API] Align schema update validations with create validations (i.e. `QuestionCreate` and `QuestionUpdate` not using validations at all) (https://github.com/argilla-io/argilla/pull/3967)
- [x] Review limits to metadata properties attributtes (name, description, allowed term values, ...) (https://github.com/argilla-io/argilla/pull/3975)
- [ ] https://github.com/argilla-io/argilla/pull/3856
- [x] Create metadata properties metrics endpoints `/api/v1/metadata-properties/:metadata_id/metrics` (https://github.com/argilla-io/argilla/pull/3856)
- [x] Always compute the total number records for `/api/v1/me/datasets/:dataset_id/records` and `/api/v1/datasets/:dataset_id/records`
- [x] Implement `__len__` method for filtered datasets using the total number of records returned by the API
- [x] Add `title` attribute for metadata properties (https://github.com/argilla-io/argilla/pull/3952)
- [x] Allow deleting metadata properties from Python sdk
- [x] Remove `type` column in metadata-properties table (https://github.com/argilla-io/argilla/pull/3956)
- [x] Allow to update a metadata property (`visible_for_annotators` and `title`) from Python SDK (https://github.com/argilla-io/argilla/pull/3953)
- [x] Add metadata SDK validation when updating records (https://github.com/argilla-io/argilla/pull/3957)
- [ ] https://github.com/argilla-io/argilla/issues/3838
- [ ] https://github.com/argilla-io/argilla/issues/3931
- [ ] https://github.com/argilla-io/argilla/pull/3932
- [ ] https://github.com/argilla-io/argilla/pull/3934
- [ ] https://github.com/argilla-io/argilla/pull/3957
- [x] Update `update_records` to use bulk endpoint
- [ ] <del>Update `allow_extra_metadata` for dataset</del>
- [ ] https://github.com/argilla-io/argilla/issues/3960
- [ ] https://github.com/argilla-io/argilla/pull/3982
- [x] Review and update the CHANGELOG.md (https://github.com/argilla-io/argilla/pull/3985)
- [x] Index metadata.name instead of metadata.id (it will simplifies the extended query feature)
- [x] Validate metadata exists on sorting and filtering (API and SDK)
- [x] DeprecatioWarning for  record.delete_suggestions
- [ ] https://github.com/argilla-io/argilla/pull/3993
- [ ] https://github.com/argilla-io/argilla/pull/3994
```

Feature branch: https://github.com/argilla-io/argilla/tree/feature/support-for-metadata-filtering-and-sorting
