### ISSUE TITLE
[FEATURE] Allow filtering and sorting using suggestions and responses

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#3849]
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/4225
- [ ] https://github.com/argilla-io/argilla/issues/4224
- [ ] https://github.com/argilla-io/argilla/issues/4226
- [ ] https://github.com/argilla-io/argilla/issues/4237
- [ ] https://github.com/argilla-io/argilla/issues/4227
- [ ] https://github.com/argilla-io/argilla/issues/4228
- [ ] https://github.com/argilla-io/argilla/issues/4229
- [ ] https://github.com/argilla-io/argilla/issues/4230
- [ ] https://github.com/argilla-io/argilla/issues/4231
- [ ] https://github.com/argilla-io/argilla/issues/4291
```

**Comment by Amelie-V** [comment]
Specs in progress

**Comment by davidberenstein1957** [comment]
@plaguss
