### ISSUE TITLE
[FEATURE] align `FeedbackRecord` with `RemoteFeedbackRecord`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3988]
**Is your feature request related to a problem? Please describe.**
- When I want to swap around `FeedbackRecord` and their equivalent `RemoteFeedbackRecord` they don't play nicely. For example, the  `RemoteFeedbackRecord` has unserializable objects.
- The `RemoteFeedbackRecord.delete()` method usage does not provide a clear overview of the fact that it return a `FeedbackRecord`.
- The `RemoteFeedbackRecord` has an `update()` method for just suggestions, but has a separate `delete_suggestions()` method. 
- The local `FeedbackRecord` only has the `update()` method, but not `__update_suggestions()` or `delete_suggestions()`.
- The local `FeedbackRecord` does not have all the properties the `RemoteFeedbackRecord` has.

**Describe the solution you'd like**
A similar approach as we did for the alignment of the datasets themselves.

**Describe alternatives you've considered**
N.A.

**Additional context**
As an internal developer, I do get why these choices were made but as a new person trying this, I think I would not understand and maybe look at something that does work out-of-the-box.

```[tasklist]
### Tasks
- [ ] align addition and update methods add_suggestions, add_responses, add_metadata
- [ ] align deletion methods
- [ ] deprecate `FeedbackRecord.update` and use validation on item assignement
```
