### ISSUE TITLE
[FEATURE] create default `text_descriptives` as metadata via `client.feedback.integrations` module

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4017]
**Is your feature request related to a problem? Please describe.**
There is sometimes too much complexity in the configuration of the FeedbackDataset using the low-level API, therefore we want to have some utils modules to guide users with an easy high-level definition of generally useful features. One of these features is the usage of basic [text descriptives](https://github.com/HLasse/TextDescriptives) as metadata for `TextFields` in the `FeedbackDataset` that highlight general info. Note that we released the metadata in `argilla==1.18`.

**Describe the solution you'd like**
Instead of manually configuring this, the API should handle 2 basic scenarios for [metadata properties](https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#define-metadata-properties). 
- Add `text-descriptives` as metadata-properties to dataset configuration.
- Add `text-descriptives` as metadata to a list of records.

For `text-descriptives` these are the things we can set:

**Language**, spaCy available models: 
df = td.extract_metrics(text=text, spacy_model="en_core_web_lg")

**Metrics**: 
```python
{'quality', 'readability', 'all', 'descriptive_stats', 'dependency_distance', 'pos_proportions', 'information_theory', 'coherence'}
```
Initially most interesting default metrics but can be simplified:

```python
{'quality',  'readability', 'descriptive_stats',  'information_theory', 'coherence'}
```

[OPTIONAL] We can also add our own attributes/measurements: for example language with langdetect or something lightweight.

**Fields**: Which fields to extract the descriptives from (if we set this at the dataset level).

**Metadata property**: As this will define a metadata property under the hood, we should be able to define the visibility (`visible_for_annotators`)

**Approach:**
I'd suggest to have different layers of complexity to setup this. The goal is to enable a very easy way to setup this for every user and give full configuration abilities to more expert users. These can be defaults:

- Our recommended selection of metrics (e.g., quality, readability, information_theory, coherence)
- `en` as language
- visible_for_annotators=True
- Apply to every field

This could look something like this but we encourage you to think critically about your own API-naming and structuring.

```python
import argilla as rg
from argilla.utils.modeling import TextDescriptives

ds = rg.FeedbackDataset(...)
td = TextDescriptives(
    model: str = `en`, 
    metrics: list[str] = ['quality',  'readability', 'descriptive_stats',  'information_theory', 'coherence'],
    visible_for_annotators: Union[bool, List[str]] = True,
    fields: Union[bool, List[str]] = True
)
# default init td = TextDescriptives() 
# separate
ds = td.update_dataset(ds)
ds = td.update_records(ds.records) # or just a list of non-dataset records
```

Take into account that we also need user-warning and errors for wrong code usage.

**Describe alternatives you've considered**
Setting this up manually. @dvsrepo can you add your code for this?

**Additional context**
[developer docs](https://docs.argilla.io/en/latest/community/developer_docs.html)
[contributor docs](https://docs.argilla.io/en/latest/community/contributing.html)

```[tasklist]
### Tasks
- [ ] define the `utils.modeling` module
- [ ] `TextDescriptives` for `update_dataset` method
- [ ] `TextDescriptives` for `update_records` method
- [ ] [optional] add `langdetect` via "language" in `metrics`
- [ ] appropriate tests in `argilla/tests/client/feedback/utils`
- [ ] update docs `create dataset` section in argilla/docs/_source
```

**Comment by dvsrepo** [comment]
@davidberenstein1957 here's the full code to add ALL text-descriptives to a dataset. I won't make sense to add all as there are too many (sometimes) overlapping measurements:

https://gist.github.com/dvsrepo/88c6897307d222fda332f1001fef6d22

**Comment by m-newhauser** [comment]
@davidberenstein1957 @dvsrepo 

When I try to add metadata to existing records in a FeedbackDataset using `.update_records()` it seems to be updating locally but the changes aren't seen in the dataset when I view it in my HF Space. How do I push these metadata changes to the version of my dataset in the HF Space?

**Comment by dvsrepo** [comment]
Hi Mary!

The update_dataset method should be defined in the new util class to be developed (you can use any other name or structure). Inside that method you can update the dataset passed as an argument. For adding metadata properties to a dataset you can [check this page](https://docs.argilla.io/en/latest/practical_guides/update_dataset.html#add-or-delete-metadata-properties). The `update_dataset` will take care of configuring the metadata properties you need for using text descriptives and `update_records` will update the records with the computed values for the configured text descriptives.

There are now two types of dataset (local and remote). Local is local instance that is not synced with the server (a local python object), you can add metadata properties, and records, but those will not be reflected in the server until you use dataset.push_to_argilla(). The remote dataset is synced with the server, and connects to an already pushed dataset. The push_to_argilla and the FeedbackDataset.from_argilla functions return the remote dataset. This object is synced with the server so if you update records and metadata properties the updates should be reflected in the server.

Hope it helps, otherwise @davidberenstein1957 can jump in and clarify the initial spec

**Comment by davidberenstein1957** [comment]
Thanks for the explanation @dvsrepo. @m-newhauser, let me know if I can clarify things a bit more.

**Comment by m-newhauser** [comment]
@dvsrepo @davidberenstein1957 
I'm getting stuck with formatting the resulting metadata from text-descriptions in a way that passes the validation checks for uploading records to Argilla. Initially, I wanted to format this data as a named nested dictionary like this:

```
RemoteFeedbackRecord(
    id=UUID('e4831b0e-c231-4c69-84d6-0518ca6023d3'), 
    client=<httpx.Client object at 0x1534e1a30>, 
    fields={'text': 'i didnt feel humiliated'}, 
    metadata={'split': 'train', 'text_descriptives': {'entropy': 0.02705801991959674, 'perplexity': 1.0274274122900553, 'per_word_perplexity': 0.20548548245801107, ...}, 
    responses=[RemoteResponseSchema(id=None, client=None, user_id=UUID('0ab9bbaf-37c8-4f6c-8b47-346617423d84'), 
    values={'label': ValueSchema(value='0')}, 
    status=<ResponseStatus.submitted: 'submitted'>, inserted_at=datetime.datetime(2023, 10, 28, 20, 57, 50, 952017),         
    updated_at=datetime.datetime(2023, 10, 28, 20, 57, 50, 952017))], suggestions=(), external_id=None)
```

But even when trying to format the metadata using Dani's [code](https://gist.github.com/dvsrepo/88c6897307d222fda332f1001fef6d22), I'm unable to transform the metadata into a format that passes validation. Instead, I'm getting a `ConfigError`:
```
ConfigError: Validators defined with incorrect fields: _validator (use check_fields=False if you're inheriting from
the model and intended this)
```
Is this because I am trying to add the new metadata as a nested dictionary? I've spent quite a while on trying to format the metadata properly and am wondering if there is additional documentation or code you can point me to or if I should move on, for now.

**Comment by davidberenstein1957** [comment]
Hi @m-newhauser , I think the metadata need to be formatted as a single `dict` with `key-value` pairs per `text-descriptive` I don't think we allow for nested `dicts`. I agree the documentation regarding metadata is a bit limited and I've been working on revamping it. Underneath, all relevant sources.

- https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#define-metadata-properties
- https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#add-records
- https://docs.argilla.io/en/latest/practical_guides/update_dataset.html#add-or-delete-metadata-properties

I think you can move on if something like this is blocking. Also, you can already create a draft-PR so we can see the process and give more specific guidance.

**Comment by dvsrepo** [comment]
For the text descriptives feature we want to use declared metadata properties (those explicitly configured at the dataset level). These are strongly typed metadata properties (terms, float, int, etc.) and cannot be populated with nested dicts. These metadata properties will be shown in the UI. There's another way of adding metadata information to records which allows for nested dicts (as far as I can tell). This is achieved by setting extra_metadata_properties to true during dataset creation ( see https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#create-the-dataset). In this way, you can add any arbitrary field/data to records during record creation, but those properties not explicitly configured via metadata properties will not be visible/filterable, they will just be stored as part of the record (something like private metadata for the dev team).

I agree this is under-documented and confusing

**Comment by dvsrepo** [comment]
@m-newhauser this colab is cleaner and might be more helpful than the one I provided on this issue some time ago: https://colab.research.google.com/drive/1-3ki6rN4FaZnxB8LBwiWjh0SMjsQdYoo?hl=es

**Comment by dvsrepo** [comment]
If we can avoid using the dataframe from text-descriptives and using spaCy directly it might be simpler and easier to maintain (avoiding datatype casting). Also feel free to pick just a selection of descriptives you find useful (as in the example above) as there are too many and it would be an overkill.

**Comment by m-newhauser** [comment]
Draft PR can be found here: https://github.com/argilla-io/argilla/pull/4083

**Comment by davidberenstein1957** [comment]
if `None` or `np.nan` values in the `df`. do they get dropped or filled with zeros. And if they are not dropped, if they are added as metadata.
