### ISSUE TITLE
[FEATURE] add a `utils` module to the package

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4030]
**Is your feature request related to a problem? Please describe.**
There are a lot of workflows that can be captured easily for community members to pick up on. 

**Describe the solution you'd like**
```python
from argilla.client.feedback.utils.html import image_to_html

image_to_html(path)
```

**Describe alternatives you've considered**
Keeping this in the docs.

**Additional context**
N.A.

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/4003
- [ ] https://github.com/argilla-io/argilla/issues/3803
- [ ] https://github.com/argilla-io/argilla/issues/3928
- [ ] https://github.com/argilla-io/argilla/issues/4031
```
