### ISSUE TITLE
[FEATURE] further aligment `FeedbackDataset` and `RemoteFeedbackDataset`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4032]
**Is your feature request related to a problem? Please describe.**
The `FeedbackDataset` and `RemoteFeedbackDataset` have some methods that are not implemented for both classes.

**Describe the solution you'd like**
I would like to see that each class and methods can be used in similar ways.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/3988
- [ ] https://github.com/argilla-io/argilla/issues/4035
- [ ] https://github.com/argilla-io/argilla/issues/4036
```
