### ISSUE TITLE
[FEATURE] implement `filter_by` for `FeedbackDataset`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4035]
**Is your feature request related to a problem? Please describe.**
Running `filter_by` does not exist.

**Describe the solution you'd like**
Have a similar behaviour as the `filter_by` for the `RemoteFeedbackDataset` but also implement more advanced methods already working locally. [This Notion](https://www.notion.so/argilla/Filtering-and-sorting-using-suggestions-and-responses-eef90b0ec7954ae6985fdbdf1c63d612?pvs=4) contains more scoping about doing this for the `RemoteFeedbackDataset`.
This should include:
- `metadata`
- `suggestions`
- `responses`
- `date-times` (inserted_at/updated_at)

**Describe alternatives you've considered**
N.A.

**Additional context**
https://docs.argilla.io/en/latest/practical_guides/filter_dataset.html#by-fields-content

```[tasklist]
### Tasks
- [ ] [FEATURE] add `metadata` to `filter_by` for `FeedbackDataset`
- [ ] [FEATURE] add `suggestions` to `filter_by` for `FeedbackDataset`
- [ ] [FEATURE] add `responses` to `filter_by` for `FeedbackDataset`
- [ ] [FEATURE] add `date_times` to `filter_by` for `FeedbackDataset`
```
