### ISSUE TITLE
Bulk annotation in Feedback datasets

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#4050]
This initial version of the bulk annotation will only apply to the `Pending` queue.

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/pull/4334
- [ ] https://github.com/argilla-io/argilla/pull/4333
- [ ] https://github.com/argilla-io/argilla/issues/4367
- [ ] https://github.com/argilla-io/argilla/issues/4449
```
