### ISSUE TITLE
[DOCS] Create and end2end `examples` directory with `.ipynb` files that align with practical guid usage.

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4178]
## Which page or section is this issue related to?
The idea is to have runnable end2end examples of basic real-life examples for the different `task-templates`, where we will initially focus on the most common task `text-classification`.

Things to keep in mind:
- they need to be executable individually but may require previous examples to be run by referencing them
- they need to be aligned with the [practical guides](https://docs.argilla.io/en/latest/practical_guides/practical_guides.html) to ensure maintainability
- it might be nice to add an [optional telemetry module](https://haystack.deepset.ai/tutorials/14_query_classifier) to see the number of usages for tutorials.
- ideally, an updated version of these tutorial datasets should be available on the Hugging Face hub as imports

<img width="720" alt="image" src="https://github.com/argilla-io/argilla/assets/25269220/ee9ddb79-1ac4-4c51-90ea-053c05f51ef4">

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/4189
- [ ] https://github.com/argilla-io/argilla/issues/4198
- [ ] https://github.com/argilla-io/argilla/issues/4179
- [ ] https://github.com/argilla-io/argilla/issues/4183
- [ ] https://github.com/argilla-io/argilla/issues/4199
- [ ] https://github.com/argilla-io/argilla/issues/4181
- [ ] https://github.com/argilla-io/argilla/issues/4182
- [ ] https://github.com/argilla-io/argilla/issues/4185
- [ ] https://github.com/argilla-io/argilla/issues/4184
- [ ] https://github.com/argilla-io/argilla/issues/4186
- [ ] https://github.com/argilla-io/argilla/issues/4187
- [ ] https://github.com/argilla-io/argilla/issues/4220
- [ ] https://github.com/argilla-io/argilla/issues/4280
```
