### ISSUE TITLE
[DOCS] add end2end example on creating a basic `text-classification` dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4179]
A part of the end2end example efforts https://github.com/argilla-io/argilla/issues/4178

https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#hugging-face-hub-datasets

```[tasklist]
### Tasks
- [x] create a text-classification dataset `for_text_classificaiton`
- [x] Upload data from https://huggingface.co/datasets/ag_news in 2 scenarios (pandas, hugging face)
- [x] upload the dataset to 2 options argilla/the hub
```
