### ISSUE TITLE
[DOCS] example on adding `metadata` to a `text-classification` dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4181]
A part of the end2end example efforts https://github.com/argilla-io/argilla/issues/4178

https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#define-metadata
https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#add-metadata

```[tasklist]
### Tasks
- [ ] Use the dataset obtained from https://github.com/argilla-io/argilla/issues/4179 by default or from the Hugging Face hub
- [ ] Show how we add metadata properties
- [ ] mention synced push to argilla and also allow push to HF
```
