### ISSUE TITLE
[DOCS] example on adding `vectors` to a `text-classification`dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4182]
A part of the end2end example efforts https://github.com/argilla-io/argilla/issues/4178

```[tasklist]
### Tasks
- [ ] Use the dataset obtained from https://github.com/argilla-io/argilla/issues/4179 by default or from the Hugging Face hub
- [ ] Show how we add vectors and setting properties
- [ ] Add basic vectors, as potentially done in our utils module https://github.com/argilla-io/argilla/issues/4018
- [ ] mention synced push to argilla and also allow push to HF
```

**Comment by sdiazlor** [comment]
@kursathalat you can use the created branch, I had only started the introduction, so you can continue from there

**Comment by davidberenstein1957** [comment]
@kursathalat , feel free to create issue for updating this and the metadata tutorial whenever the modules are done.
