### ISSUE TITLE
[DOCS] example on updating records with `suggestions` and `responses` for a `text-classification` dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4183]
A part of the end2end example efforts https://github.com/argilla-io/argilla/issues/4178

https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#add-records

```[tasklist]
### Tasks
- [ ] Use the dataset obtained from https://github.com/argilla-io/argilla/issues/4179 by default or from the Hugging Face hub
- [ ] Show how we might use the AG-news dataset for the officially annotated responses
- [ ] Show how me might use a `NLI` model to asses labels for suggestions
- [ ] update the records for them 
- [ ] mention synced push to argilla and also allow push to HF
```

**Comment by davidberenstein1957** [comment]
You can do a `pull()` -> to convert to local. Do a `push()` after. 

Also, feel free to create a new github to update this tutorial whenever we have `update_records` for responses.
