### ISSUE TITLE
[DOCS] example on assigning record to your team for a `text-classification` dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4184]
A part of the end2end example efforts https://github.com/argilla-io/argilla/issues/4178

https://docs.argilla.io/en/v1.19.0/practical_guides/assign_records.html

```[tasklist]
### Tasks
- [ ] Use the dataset obtained from https://github.com/argilla-io/argilla/issues/4179 by default or from the Hugging Face hub
- [ ] Show how we to assign based on different dataset and overlap
- [ ] Show how to assign based on metadata?
- [ ] mention synced push to argilla but no push to Hugging Face
```
This is the end of one of the flows because it becomes to niche/custom to cover in steps later on
