### ISSUE TITLE
[DOCS] example on metrics for a `text-classification` dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4186]
A part of the end2end example efforts https://github.com/argilla-io/argilla/issues/4178

https://docs.argilla.io/en/latest/practical_guides/collect_responses.html

```[tasklist]
### Tasks
- [ ] Use the dataset obtained from https://github.com/argilla-io/argilla/issues/4183 by default or from the Hugging Face hub
- [ ] Show how we might to unify records
- [ ] Show how to compute metrics with https://github.com/argilla-io/argilla/issues/4034
```

We don't push to Argilla because this is the end of a flow and too niche to cover.

**Comment by davidberenstein1957** [comment]
create a branch from the metrics module branch and create documentation and also this tutorial
