### ISSUE TITLE
[DOCS] example on fine-tuning for a `text-classification` dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4187]
A part of the end2end example efforts https://github.com/argilla-io/argilla/issues/4178

https://docs.argilla.io/en/latest/practical_guides/fine_tune.html

```[tasklist]
### Tasks
- [ ] Use the dataset obtained from https://github.com/argilla-io/argilla/issues/4183 by default or from the Hugging Face hub
- [ ] Show how we might use the trainer with defaults
- [ ] Show how we might use the trainer with a custom func
- [ ] Show how to push the model to the hub
```

We don't push to Argilla because this is the end of a flow and too niche to cover.
