### ISSUE TITLE
[FEATURE] Shortcuts new generation

### ISSUE THREAD

**Issue by damianpumar** [recognai/rubrix#4221]
**When the form has only 1 single label / rating question:**

```[tasklist]
### Tasks
- [x] Automatically submit when an option is selected.
- [x] Show the key number associated with each single / multi label question
- [x] Add this new shortcut to the legend
- [x] Show all keys for all single / multi label questions
- [x] Submit: `Enter` (active when all required responses are done)
- [x] Discard: `Backspace` (active when all required responses are done)
- [x] Clear: Remove shortcuts
- [x] TextArea: To focus on: `Shift + Enter`
- [x] TextArea: To leave it: `Escape`
- [x] If text area is not required do not focus automatically. In that case users can press directly on Enter to submit.
- [ ] Update documentation
- [x] Remove `Clear` button shortcut
- [x] Remove cmd/ctrl for pagination
- [x] Legend visible by default
- [x] When a mandatory text field contains a suggestion or an existing value we don’t focus automatically on the text area by default (especially useful when only one mandatory text field)
- [x] Remove `Unrank` with `Backspace` because now it's assigned to `Discard`
```
