### ISSUE TITLE
[FEATURE] Support filter and sort as part of the request body for search endpoints

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4227]
```[tasklist]
### Tasks
- [x] Define `filters` and `sort` pydantic schemas #4270
- [x] Change `POST /api/v1/me/datasets/:dataset_id/records/search`
- [x] Change `POST /apo/v1/datasets/:dataset_id/records/search`
- [ ] https://github.com/argilla-io/argilla/issues/4228
- [ ] https://github.com/argilla-io/argilla/issues/4229
- [ ] https://github.com/argilla-io/argilla/pull/4327
```
