### ISSUE TITLE
[FEATURE] Integrate new filter and sort in search engine

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4228]
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/pull/4292
- [ ] https://github.com/argilla-io/argilla/pull/4305
- [ ] https://github.com/argilla-io/argilla/pull/4309
```
