### ISSUE TITLE
[DOCS] [UI] Improve No dataset page to transform it into an onboarding page for first time users (developers)

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4274]
# Definition
We will remove :warning: signs, negative statements, broad URLs (like [docs.argilla.io](http://docs.argilla.io/)) right at the beginning. 

All the explanations should be made on clear text not code comments. 

And then the structure should be:

1. Welcome the user, explain how is easy is to get started, and explain how to get started step-by-step, and making sure the code snippets we suggest really work (at least in most cases).
2. We should avoid as much as possible requiring external deps.
3. The steps can be something like:
4. Open a notebook or Colab (we can even add the link to open a colab)
5. Install the argilla client with pip
6. Connect to the server with init, I guess we can't be 100% sure about the api_url but we can explain. For the api_key, explain the user where to get it in the UI with a link.
7. Setup and create your first dataset with records. We can use something that's really easy, doesn't require deps (if possible) and gets the user a first taste of how a simple dataset looks like.
8. Explain next steps, as you mentioned pointing to end to end examples

```[tasklist]
### Tasks
- [ ]  @leiyre will remove the hard-coded top content  (stop sign, there aren't any datasets, etc.) leaving only the section where we render markdown
- [ ]  @sdiazlor will create an initial md document with clear sections, links, code snippets, based on the structure above https://github.com/argilla-io/argilla/blob/develop/docs/_source/_common/snippets/start_page.md
- [ ] -@davidberenstein1957 and @dvsrepo will review the onboarding content.
- [ ] @Amelie-V and @leiyre will fine-tune the styles of the rendered markdown if needed.

```

**Comment by nataliaElv** [comment]
Maybe @Amelie-V wants to comment on the definition and design of this page.

**Comment by davidberenstein1957** [comment]
That would be great. The steps above were initially introduced by @dvsrepo

**Comment by Amelie-V** [comment]
If it does not impact only the docs but the UI too, it should enter in triage before to be assign to a milestone.

**Comment by davidberenstein1957** [comment]
https://docs.argilla.io/en/develop/getting_started/quickstart.html

**Comment by davidberenstein1957** [comment]
@Amelie-V 
![image](https://github.com/argilla-io/argilla/assets/25269220/af543366-51d9-4501-9783-d324b6978c6c)

**Comment by Amelie-V** [comment]
We'll wait for the review of the text (Task 3) to work on styles.
