### ISSUE TITLE
[FEATURE] update the way we label in github 

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4312]
**Is your feature request related to a problem? Please describe.**
assign labels
- for people outside of the organization
- active involvement issues

**Describe the solution you'd like**
N.A.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

```[tasklist]
### Tasks
- [x] update `.github/workflow` to auto-label certain issues
- [x] review label schemas to simplify and adhere to "{category}: {name}"
- [x] try to comeup with active issue labeler
- [x] update the issue templates
- [x] update the boards
```
