### ISSUE TITLE
[FEATURE] Separate argilla server package

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4468]
Create a separate package for all related Argilla server functionality.

The main argilla module will use the server package as a normal dependency:
```toml
#pyproject.toml

[project.optional-dependencies]
server = [
  "argilla-server~=X.Y.Z"
]
```

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/4470
- [ ] https://github.com/argilla-io/argilla/issues/4469
- [ ] https://github.com/argilla-io/argilla/issues/4471
- [ ] https://github.com/argilla-io/argilla/issues/4479
- [ ] https://github.com/argilla-io/argilla/issues/4536
```
