### ISSUE TITLE
[FEATURE] Allow to change the title of labels

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4558]
**Description**

As an admin, I want to be able to change the titles of labels so that I can make corrections in case there are any typos or I find a more user-friendly name for my labels.

**Acceptance criteria**
- [ ] Label names and titles are visible in the Questions tab of the Dataset Settings Page for questions of the following types: `Label`, `MultiLabel`, `Ranking` and `Spans` or `HierarchichalLabel` if available. 
- [ ] Admins and owners can change label titles and save those changes 
- [ ] Label names are visible, but they cannot be changed.
- [ ] I can see the new label title in the preview as I change it. 
- [ ] Users of any role can see the new label titles in the Questions form (in all status queues) and in the Responses and Suggestions filters.

```[tasklist]
### Tasks
```
