### ISSUE TITLE
[FEATURE] Add score attribute for suggestions associated to a multi label question

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#4638]
For the new feature adding support for span questions we will give support to specify a `score` for suggestions associated to a span question.

For that we are following the next format (PUT to upsert a suggestion):

```json
{
    "question_id": "id-of-the-question",
    "type": "model",
    "value": [
        {"label": "label-a", "start": 0, "end": 1, "score": 0.2},
        {"label": "label-b", "start": 2, "end": 3, "score": 1},
        {"label": "label-c", "start": 4, "end": 5},
    ]
}
```

For this issue we should add `score` attribute for suggestions associated to a `multi_label_selection` question too. With this change users can specify a `score` value for every label inside the suggestion.

Additional points to research/discuss:
* Changes to the SDK.
* Changes related to UI. Are we gonna show this information in the UI?

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla-server/issues/93
- [ ] https://github.com/argilla-io/argilla-server/issues/113
- [ ] https://github.com/argilla-io/argilla-server/issues/128
- [ ] https://github.com/argilla-io/argilla-server/issues/99
- [ ] https://github.com/argilla-io/argilla/issues/4724
- [ ] https://github.com/argilla-io/argilla/issues/4725
```
