### ISSUE TITLE
[FEATURE] provide a warning if persistent storage has not been enabled.

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4684]
**Is your feature request related to a problem? Please describe.**
Within the `Docker` deployments on HF and others (I would say everything `not k8s`), we've got an issue of people not realising they need persistent storage to retain annotation responses.

**Describe the solution you'd like**
 I would consider adding a `PERSISTENT_STORAGE_ENABLED=False` env var that shows a small UI pop up whenever someone has not spend time thinking about this.

**Describe alternatives you've considered**
N.A.

**Additional context**
This has happened multiple times during the DIBT efforts and also in the past to community members.
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla-server/issues/120
- [ ] https://github.com/argilla-io/argilla-server/issues/123
- [ ] https://github.com/argilla-io/argilla-server/issues/126
- [ ] https://github.com/argilla-io/argilla/issues/4743
- [ ] https://github.com/argilla-io/argilla/issues/4736
```

**Comment by davidberenstein1957** [comment]
`PERSISTANT_STORAGE_ENABLED` can be used as environment variable to show or not show a warning.

**Comment by davidberenstein1957** [comment]
The main idea, show a warning within the UI that shows something like "Missing persistant storage and riskt of loosing annotated data" whenever the environment variable `PERSISTANT_STORAGE_ENABLED` has not been set.

This should cover 2 flows.
- Hugging Face deployments set this variable through `PERSISTANT_STORAGE_ENABLED` when someone enables this from their UI, if not it will automatically show the error message above to emphasize the risk.
- All other deployments in any other place will have `PERSISTANT_STORAGE_ENABLED=False` by default to ensure that people will explicitly need to set the environment variable to be aware they might loose data or at least to emphasize that someone should spend time on actively changing this environment variable to avoid doing that.

**Comment by davidberenstein1957** [comment]
Update: internally we can use  `SHOW_PERSISTENT_STORE_WARNING` but from the HF side `PERSISTANT_STORAGE_ENABLED` is fixed so we can have some logic surrounding these two examples. Having `SHOW_PERSISTENT_STORE_WARNING` can also be used for forcefully disabling this message.

**Comment by davidberenstein1957** [comment]
Update:  I believe it should be quite clear something in the config has not gone correctly so
- Every type of role should be able to see it.
- Every time they open the platform the pop-up can be shown
