### ISSUE TITLE
[FEATURE] Dataset overall progress bar

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4691]
**Is your feature request related to a problem? Please describe.**
- As an admin, I want to see the overall progress of the dataset, so I know much is left to complete the dataset.
- An an annotator, I want to see the overall progress of the datasets that I have access to, so I can make a more informed strategic decision on what to work on next based on where I can make the most impact.

**Describe the solution you'd like**
![Screenshot 2024-03-27 at 12 12 48](https://github.com/argilla-io/argilla/assets/126158523/d5806bb9-8274-4b37-b4a7-1376384ae413)

```[tasklist]
### Acceptance criteria
- [ ] Show the overall progress bar to all users with access to the dataset.
- [ ] The progress bar will live in a column in the home page (as a substitute of the tags column).
- [ ] The progress bar will show: submitted, discarded and what's left.
- [ ] The information will be shown following the design above, note that there will be a percentage, but also a fraction with real numbers in a tooltip when hovering over each of the sections in the progress bar.
- [ ] The number of left records will appear at first sight next to the progress bar.
- [ ] Each record in the dataset will belong to **only one** of the three categories.
- [ ] Submitted = any record with at least 1 submitted response but no discarded
- [ ] Conflicting = any records with at least 1 submitted and 1 discarded response
- [ ] Discarded = any record with at least 1 discarded but no submitted
- [ ] Left / Remaining = the remaining records. These will be records where none of the responses are submitted or discarded == all responses are in draft status or have no responses at all (i.e. pending).
```

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla-server/issues/91
- [ ] [TASK] Add cache to functions calculating dataset progress
```

**Comment by nataliaElv** [comment]
Related to argilla-io/argilla#3882
