### ISSUE TITLE
[FEATURE] `ImageField` 

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4823]
**Is your feature request related to a problem? Please describe.**
Using `TextField` with markdown enabled is a hacky way of having images in Argilla. We'd prefer to have a proper way to render images to work with multi-modal models and datasets.

**Describe the solution you'd like**
An `ImageField` where it's possible to include images in different formats.

**Describe alternatives you've considered**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/5276
```

```[tasklist]
### SDK
- [ ] https://github.com/argilla-io/argilla/issues/5277
```

```[tasklist]
### Frontend
- [ ] https://github.com/argilla-io/argilla/issues/5278
```

**Comment by JonnyTran** [comment]
Wanted to link my opened issue https://github.com/argilla-io/argilla/issues/4739 about an image bbox feature suggestion here 🙂
