### ISSUE TITLE
Migrate `argilla-python` SDK to `argilla` repo

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4888]
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/4895
- [ ] https://github.com/argilla-io/argilla/issues/4923
- [ ] https://github.com/argilla-io/argilla/issues/4926
- [ ] https://github.com/argilla-io/argilla/issues/4924
- [ ] https://github.com/argilla-io/argilla/issues/4925
```
