### ISSUE TITLE
[TASK] Argilla server technical debt

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#4914]
This is a global issue to help us organize different tasks related with technical debt on argilla-server.
```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla/issues/4916
- [ ] https://github.com/argilla-io/argilla/issues/4918
- [ ] https://github.com/argilla-io/argilla/issues/4881
- [ ] https://github.com/argilla-io/argilla/issues/4965
- [ ] [TASK] Move telemetry calls to context functions
```
