### ISSUE TITLE
[FEAT] [SDK] Implement external integrations 

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4949]
Generally the integrations need to be made and updated to Argilla 2.0

Things to keep in mind:
- logic and showcases for integrations should be kept in the repo for those integrations to avoid duplication. Perhaps core implementations like Argilla metris can be used in the docs.
- Integrations should be testable through CICD in GH

```[tasklist]
### Tasks
- [ ] distilabel
- [ ] argilla-metrics (
- [ ] argilla-text-descriptives
- [ ] argilla-sentence-transformers
- [x] argilla-llama-index
- [ ] argilla-haystack
- [ ] argilla-unstructured https://github.com/Unstructured-IO/unstructured/pull/1173
```

**Comment by davidberenstein1957** [comment]
Also consider the docs https://github.com/argilla-io/argilla/issues/4950

**Comment by burtenshaw** [comment]
@nataliaElv Move this to 2.1
