### ISSUE TITLE
[DOCS] Add integrations to new documentation

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4950]
Generally the integrations need to be made and updated to Argilla 2.0

Things to keep in mind:
- logic and showcases for integrations should be kept in the repo for those integrations to avoid duplication. Perhaps core implementations like Argilla metris can be used in the docs.

```[tasklist]
### Tasks
- [ ] distilabel
- [ ] argilla-metrics
- [ ] argilla-text-descriptives
- [ ] argilla-sentence-transformers
- [x] argilla-llama-index
- [ ] argilla-haystack
- [ ] argilla-unstructured
```

**Comment by nataliaElv** [comment]
@davidberenstein1957 I think we can safely transfer this issue to the `argilla` repo, but please confirm.

**Comment by burtenshaw** [comment]
@nataliaElv Move this to 2.1
